#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.0 on Mon Apr 14 21:05:37 2025
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class PluginFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: PluginFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((850, 625))
        self.SetTitle("Plugin Loader")
        self.SetBackgroundColour(wx.Colour(221, 199, 183))

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        self.notebook_1 = wx.Notebook(self.panel_1, wx.ID_ANY)
        sizer_1.Add(self.notebook_1, 1, wx.EXPAND, 0)

        self.notebook_1_pane_plugin = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1.AddPage(self.notebook_1_pane_plugin, "Plugins")

        sizer_3 = wx.BoxSizer(wx.VERTICAL)

        label_1 = wx.StaticText(self.notebook_1_pane_plugin, wx.ID_ANY, "VST/LV2")
        label_1.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_3.Add(label_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.list_box_vst_lv2 = wx.ListBox(self.notebook_1_pane_plugin, wx.ID_ANY, choices=[], style=wx.LB_SINGLE | wx.LB_SORT)
        self.list_box_vst_lv2.SetMinSize((900, 400))
        self.list_box_vst_lv2.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Noto Sans"))
        self.list_box_vst_lv2.SetToolTip("Double-Click or Enter to load the selection")
        sizer_3.Add(self.list_box_vst_lv2, 1, wx.EXPAND | wx.LEFT | wx.RIGHT, 3)

        sizer_4 = wx.FlexGridSizer(1, 7, 0, 0)
        sizer_3.Add(sizer_4, 1, wx.ALIGN_CENTER_HORIZONTAL | wx.LEFT | wx.TOP, 2)

        self.button_connect = wx.Button(self.notebook_1_pane_plugin, wx.ID_ANY, "Connect")
        self.button_connect.SetMinSize((120, 25))
        self.button_connect.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        self.button_connect.SetToolTip("Try to connect ports to audio interface")
        sizer_4.Add(self.button_connect, 0, wx.ALIGN_CENTER | wx.RIGHT, 5)

        self.checkbox_autoconnect = wx.CheckBox(self.notebook_1_pane_plugin, wx.ID_ANY, "Auto Connect")
        self.checkbox_autoconnect.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        self.checkbox_autoconnect.SetToolTip("Try to auto connect")
        sizer_4.Add(self.checkbox_autoconnect, 0, wx.ALIGN_CENTER | wx.RIGHT, 5)

        static_line_4 = wx.StaticLine(self.notebook_1_pane_plugin, wx.ID_ANY, style=wx.LI_VERTICAL)
        sizer_4.Add(static_line_4, 0, wx.EXPAND | wx.LEFT | wx.RIGHT, 5)

        self.checkbox_jalv = wx.CheckBox(self.notebook_1_pane_plugin, wx.ID_ANY, "Run LV2 on Jalv")
        self.checkbox_jalv.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        self.checkbox_jalv.SetToolTip("Run LV2 in Jalv")
        sizer_4.Add(self.checkbox_jalv, 0, wx.ALIGN_CENTER | wx.RIGHT, 5)

        static_line_8 = wx.StaticLine(self.notebook_1_pane_plugin, wx.ID_ANY, style=wx.LI_VERTICAL)
        sizer_4.Add(static_line_8, 0, wx.EXPAND | wx.LEFT | wx.RIGHT, 5)

        label_3 = wx.StaticText(self.notebook_1_pane_plugin, wx.ID_ANY, "Carla arch:")
        label_3.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_4.Add(label_3, 0, wx.ALIGN_CENTER | wx.LEFT | wx.RIGHT, 4)

        self.combo_box_arch = wx.ComboBox(self.notebook_1_pane_plugin, wx.ID_ANY, choices=["native", "win64", "win32"], style=wx.CB_DROPDOWN)
        self.combo_box_arch.SetMinSize((105, 25))
        self.combo_box_arch.SetToolTip("Select Vst arch")
        self.combo_box_arch.SetSelection(0)
        sizer_4.Add(self.combo_box_arch, 0, wx.ALIGN_CENTER | wx.LEFT | wx.RIGHT, 2)

        grid_sizer_2 = wx.FlexGridSizer(1, 3, 0, 0)
        sizer_3.Add(grid_sizer_2, 1, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.search_ctrl_1 = wx.SearchCtrl(self.notebook_1_pane_plugin, wx.ID_ANY, "")
        self.search_ctrl_1.SetMinSize((200, 25))
        self.search_ctrl_1.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Noto Sans"))
        self.search_ctrl_1.SetToolTip("Filter the listboxes")
        self.search_ctrl_1.ShowCancelButton(True)
        grid_sizer_2.Add(self.search_ctrl_1, 0, wx.ALIGN_CENTER | wx.RIGHT, 2)

        static_line_6 = wx.StaticLine(self.notebook_1_pane_plugin, wx.ID_ANY, style=wx.LI_VERTICAL)
        grid_sizer_2.Add(static_line_6, 0, wx.EXPAND | wx.LEFT | wx.RIGHT, 5)

        self.button_kill_apps = wx.Button(self.notebook_1_pane_plugin, wx.ID_ANY, "Kill Apps")
        self.button_kill_apps.SetMinSize((200, 25))
        self.button_kill_apps.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        self.button_kill_apps.SetToolTip("Kill all running apps")
        grid_sizer_2.Add(self.button_kill_apps, 0, wx.ALIGN_CENTER, 2)

        self.notebook_1_pane_setup = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1.AddPage(self.notebook_1_pane_setup, "Setup")

        sizer_5 = wx.GridSizer(3, 1, 0, 0)

        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5.Add(sizer_6, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        label_4 = wx.StaticText(self.notebook_1_pane_setup, wx.ID_ANY, "Vst2 Directories")
        label_4.SetMinSize((108, 866))
        label_4.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_6.Add(label_4, 0, wx.ALL | wx.EXPAND, 3)

        self.list_box_vst2_directories = wx.ListBox(self.notebook_1_pane_setup, wx.ID_ANY, choices=[], style=wx.LB_MULTIPLE | wx.LB_SORT)
        self.list_box_vst2_directories.SetMinSize((520, 145))
        self.list_box_vst2_directories.SetFont(wx.Font(9, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        self.list_box_vst2_directories.SetToolTip("Directories that contains the Vst2")
        sizer_6.Add(self.list_box_vst2_directories, 0, wx.ALL, 4)

        sizer_7 = wx.BoxSizer(wx.VERTICAL)
        sizer_6.Add(sizer_7, 1, 0, 0)

        self.button_select_vst2 = wx.Button(self.notebook_1_pane_setup, wx.ID_ANY, "Select New")
        self.button_select_vst2.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Noto Sans"))
        sizer_7.Add(self.button_select_vst2, 0, wx.ALL, 3)

        self.button_delete_vst2 = wx.Button(self.notebook_1_pane_setup, wx.ID_ANY, "Remove")
        self.button_delete_vst2.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Noto Sans"))
        sizer_7.Add(self.button_delete_vst2, 0, wx.ALL, 3)

        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5.Add(sizer_8, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        label_5 = wx.StaticText(self.notebook_1_pane_setup, wx.ID_ANY, "Vst3 Directories")
        label_5.SetMinSize((108, 866))
        label_5.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_8.Add(label_5, 0, wx.ALL | wx.EXPAND, 3)

        self.list_box_vst3_directories = wx.ListBox(self.notebook_1_pane_setup, wx.ID_ANY, choices=[], style=wx.LB_MULTIPLE | wx.LB_SORT)
        self.list_box_vst3_directories.SetMinSize((520, 145))
        self.list_box_vst3_directories.SetFont(wx.Font(9, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        self.list_box_vst3_directories.SetToolTip("Directories that contains the Vst3")
        sizer_8.Add(self.list_box_vst3_directories, 0, wx.ALL, 4)

        sizer_9 = wx.BoxSizer(wx.VERTICAL)
        sizer_8.Add(sizer_9, 1, 0, 0)

        self.button_select_vst3 = wx.Button(self.notebook_1_pane_setup, wx.ID_ANY, "Select New")
        self.button_select_vst3.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Noto Sans"))
        sizer_9.Add(self.button_select_vst3, 0, wx.ALL, 3)

        self.button_delete_vst3 = wx.Button(self.notebook_1_pane_setup, wx.ID_ANY, "Remove")
        self.button_delete_vst3.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Noto Sans"))
        sizer_9.Add(self.button_delete_vst3, 0, wx.ALL, 3)

        grid_sizer_1 = wx.GridSizer(3, 4, 0, 0)
        sizer_5.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        label_6 = wx.StaticText(self.notebook_1_pane_setup, wx.ID_ANY, "Keyboard Substring", style=wx.ALIGN_RIGHT)
        label_6.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        grid_sizer_1.Add(label_6, 0, wx.ALL | wx.EXPAND, 7)

        self.text_ctrl_keyboard_substring = wx.TextCtrl(self.notebook_1_pane_setup, wx.ID_ANY, "")
        self.text_ctrl_keyboard_substring.SetMinSize((150, 32))
        self.text_ctrl_keyboard_substring.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Noto Sans"))
        self.text_ctrl_keyboard_substring.SetToolTip("Substring of the jack name of the MIDI keyboard")
        grid_sizer_1.Add(self.text_ctrl_keyboard_substring, 0, wx.ALL, 3)

        label_7 = wx.StaticText(self.notebook_1_pane_setup, wx.ID_ANY, "Teminal (Console)", style=wx.ALIGN_RIGHT)
        label_7.SetMinSize((108, 866))
        label_7.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        grid_sizer_1.Add(label_7, 0, wx.ALL | wx.EXPAND, 7)

        self.combo_box_terminal = wx.ComboBox(self.notebook_1_pane_setup, wx.ID_ANY, choices=["-", "uxterm", "xterm", "konsole"], style=wx.CB_DROPDOWN | wx.TE_PROCESS_ENTER)
        self.combo_box_terminal.SetMinSize((150, 32))
        self.combo_box_terminal.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Noto Sans"))
        self.combo_box_terminal.SetToolTip("Terminal app to use. \nTo set a terminal not listed in the combo type the executable name and press Enter/Return.")
        self.combo_box_terminal.SetSelection(0)
        grid_sizer_1.Add(self.combo_box_terminal, 0, 0, 0)

        label_9 = wx.StaticText(self.notebook_1_pane_setup, wx.ID_ANY, "Interface Substring", style=wx.ALIGN_RIGHT)
        label_9.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        grid_sizer_1.Add(label_9, 0, wx.ALL | wx.EXPAND, 7)

        self.text_ctrl_interface_substring = wx.TextCtrl(self.notebook_1_pane_setup, wx.ID_ANY, "")
        self.text_ctrl_interface_substring.SetMinSize((150, 32))
        self.text_ctrl_interface_substring.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Noto Sans"))
        self.text_ctrl_interface_substring.SetToolTip("Substring of the audio interface used (if empty the app will select the first one find).")
        grid_sizer_1.Add(self.text_ctrl_interface_substring, 0, wx.ALL, 3)

        self.checkbox_load_vst = wx.CheckBox(self.notebook_1_pane_setup, wx.ID_ANY, "Load VST2/3")
        self.checkbox_load_vst.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        self.checkbox_load_vst.SetValue(1)
        grid_sizer_1.Add(self.checkbox_load_vst, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 3)

        self.checkbox_load_lv2 = wx.CheckBox(self.notebook_1_pane_setup, wx.ID_ANY, "Load LV2")
        self.checkbox_load_lv2.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        self.checkbox_load_lv2.SetValue(1)
        grid_sizer_1.Add(self.checkbox_load_lv2, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 3)

        label_8 = wx.StaticText(self.notebook_1_pane_setup, wx.ID_ANY, "Auto Connections Retry", style=wx.ALIGN_RIGHT)
        label_8.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        grid_sizer_1.Add(label_8, 0, wx.ALL | wx.EXPAND, 7)

        self.combo_box_autoconnect_retry = wx.ComboBox(self.notebook_1_pane_setup, wx.ID_ANY, choices=["1", "2", "3", "4"], style=wx.CB_DROPDOWN)
        self.combo_box_autoconnect_retry.SetMinSize((150, 32))
        self.combo_box_autoconnect_retry.SetToolTip("Number iteractions for connections")
        self.combo_box_autoconnect_retry.SetSelection(1)
        grid_sizer_1.Add(self.combo_box_autoconnect_retry, 0, wx.ALL, 3)

        label_10 = wx.StaticText(self.notebook_1_pane_setup, wx.ID_ANY, "Audio Connections", style=wx.ALIGN_RIGHT)
        label_10.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        grid_sizer_1.Add(label_10, 0, wx.ALL | wx.EXPAND, 7)

        self.combo_box_audio_connections = wx.ComboBox(self.notebook_1_pane_setup, wx.ID_ANY, choices=["1", "2", "3", "4"], style=wx.CB_DROPDOWN)
        self.combo_box_audio_connections.SetMinSize((150, 32))
        self.combo_box_audio_connections.SetToolTip("Number audio ports to connect")
        self.combo_box_audio_connections.SetSelection(1)
        grid_sizer_1.Add(self.combo_box_audio_connections, 0, wx.ALL, 3)

        self.notebook_1_About = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1.AddPage(self.notebook_1_About, "About")

        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)

        label_2 = wx.StaticText(self.notebook_1_About, wx.ID_ANY, "This program uses carla-single to load installed LV2 and VST plugins as standalone apps. Optionally, Jalv can be used for LV2 plugins.\n\nTab 1: Plugins\nThis tab lists all detected plugins. Launch a plugin by double-clicking it or pressing Enter.\nConnect: Attempts to link audio and MIDI ports to JACK.\nAutoconnect: Automatically connects ports after launching a plugin (may cause hangs on KDE).\nRun LV2 on Jalv: Launches LV2 plugins using Jalv instead of carla-single.\nCarla Arch: Sets the architecture used for loading VSTs.\nSearch: Filters plugins by name.\nKill Apps: Sends a termination signal to any plugin process started by the app.\n\nTab 2: Setup\nThis section allows configuration of plugin paths and connection settings.\nVST2/3 Directories: Add folders containing VST plugins, including those for Yabridge or Windows.\nKeyboard/Interface Substring: Enter part of the JACK name for MIDI/Audio interfaces to use with the Connect feature.\nAudio Connections Retry: Number of attempts to connect audio ports (recommended: 2).\nTerminal (Console): Optional terminal application to use.\nLoad VST2/3 / Load LV2: Select which plugin types to load.\nAudio Connections: Define how many audio hardware ports to connect.\n\nVersion 0.02")
        sizer_2.Add(label_2, 0, 0, 0)

        self.notebook_1_About.SetSizer(sizer_2)

        self.notebook_1_pane_setup.SetSizer(sizer_5)

        grid_sizer_2.AddGrowableCol(1)

        self.notebook_1_pane_plugin.SetSizer(sizer_3)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()
        self.Centre()

        self.list_box_vst_lv2.Bind(wx.EVT_LISTBOX_DCLICK, self.listbox_vst_lv2_double_click)
        self.button_connect.Bind(wx.EVT_BUTTON, self.connect_jack)
        self.combo_box_arch.Bind(wx.EVT_COMBOBOX, self.combobox_change_arch)
        self.search_ctrl_1.Bind(wx.EVT_TEXT, self.vst_search)
        self.button_kill_apps.Bind(wx.EVT_BUTTON, self.kill_apps)
        self.button_select_vst2.Bind(wx.EVT_BUTTON, self.vst2_select_new)
        self.button_delete_vst2.Bind(wx.EVT_BUTTON, self.vst2_remove)
        self.button_select_vst3.Bind(wx.EVT_BUTTON, self.vst3_select_new)
        self.button_delete_vst3.Bind(wx.EVT_BUTTON, self.vst3_remove)
        self.text_ctrl_keyboard_substring.Bind(wx.EVT_TEXT, self.set_keyboard_subtring)
        self.combo_box_terminal.Bind(wx.EVT_COMBOBOX, self.set_terminal)
        self.combo_box_terminal.Bind(wx.EVT_TEXT_ENTER, self.add_terminal)
        self.text_ctrl_interface_substring.Bind(wx.EVT_TEXT, self.set_interface_subtring)
        self.checkbox_load_vst.Bind(wx.EVT_CHECKBOX, self.set_load_vst)
        self.checkbox_load_lv2.Bind(wx.EVT_CHECKBOX, self.set_load_lv2)
        self.combo_box_autoconnect_retry.Bind(wx.EVT_COMBOBOX, self.set_autoconnect)
        self.combo_box_audio_connections.Bind(wx.EVT_COMBOBOX, self.set_audioconnections)
        # end wxGlade

    def listbox_vst_lv2_double_click(self, event):  # wxGlade: PluginFrame.<event_handler>
        print("Event handler 'listbox_vst_lv2_double_click' not implemented!")
        event.Skip()

    def connect_jack(self, event):  # wxGlade: PluginFrame.<event_handler>
        print("Event handler 'connect_jack' not implemented!")
        event.Skip()

    def combobox_change_arch(self, event):  # wxGlade: PluginFrame.<event_handler>
        print("Event handler 'combobox_change_arch' not implemented!")
        event.Skip()

    def vst_search(self, event):  # wxGlade: PluginFrame.<event_handler>
        print("Event handler 'vst_search' not implemented!")
        event.Skip()

    def kill_apps(self, event):  # wxGlade: PluginFrame.<event_handler>
        print("Event handler 'kill_apps' not implemented!")
        event.Skip()

    def vst2_select_new(self, event):  # wxGlade: PluginFrame.<event_handler>
        print("Event handler 'vst2_select_new' not implemented!")
        event.Skip()

    def vst2_remove(self, event):  # wxGlade: PluginFrame.<event_handler>
        print("Event handler 'vst2_remove' not implemented!")
        event.Skip()

    def vst3_select_new(self, event):  # wxGlade: PluginFrame.<event_handler>
        print("Event handler 'vst3_select_new' not implemented!")
        event.Skip()

    def vst3_remove(self, event):  # wxGlade: PluginFrame.<event_handler>
        print("Event handler 'vst3_remove' not implemented!")
        event.Skip()

    def set_keyboard_subtring(self, event):  # wxGlade: PluginFrame.<event_handler>
        print("Event handler 'set_keyboard_subtring' not implemented!")
        event.Skip()

    def set_terminal(self, event):  # wxGlade: PluginFrame.<event_handler>
        print("Event handler 'set_terminal' not implemented!")
        event.Skip()

    def add_terminal(self, event):  # wxGlade: PluginFrame.<event_handler>
        print("Event handler 'add_terminal' not implemented!")
        event.Skip()

    def set_interface_subtring(self, event):  # wxGlade: PluginFrame.<event_handler>
        print("Event handler 'set_interface_subtring' not implemented!")
        event.Skip()

    def set_load_vst(self, event):  # wxGlade: PluginFrame.<event_handler>
        print("Event handler 'set_load_vst' not implemented!")
        event.Skip()

    def set_load_lv2(self, event):  # wxGlade: PluginFrame.<event_handler>
        print("Event handler 'set_load_lv2' not implemented!")
        event.Skip()

    def set_autoconnect(self, event):  # wxGlade: PluginFrame.<event_handler>
        print("Event handler 'set_autoconnect' not implemented!")
        event.Skip()

    def set_audioconnections(self, event):  # wxGlade: PluginFrame.<event_handler>
        print("Event handler 'set_audioconnections' not implemented!")
        event.Skip()

# end of class PluginFrame

class MyApp(wx.App):
    def OnInit(self):
        self.frame = PluginFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    plugin_loader = MyApp(0)
    plugin_loader.MainLoop()
